### ISSUE TITLE
Are the attributes 'reactive'?

### ISSUE THREAD

**Issue by gavinr** [jf990/esri-map-component#39]
I've tried out this component, and it works great for getting a quick map on the page.

After I set up a basic example, I was curious if I could use the attributes in a "reactive" way - that is, if I change the attribute, would the map on the page change. I created this sample to test if I change the basemap attribute on the custom element, will the basemap change visually in the map? It looks like it does not: 

https://codepen.io/gavinr/pen/yLxEVvp?editors=0010
- Click on "Imagery" button
    - expected: when clicking "imagery" button the map's basemap should visually change to imagery
    - actual: clicking the "imagery" button changes the attribute but the basemap does not change

**Comment by jf990** [comment]
@gavinr thanks, this is a good idea I will look into it. My objective was to create a component to simply and easily get a map on a web page without writing any JavaScript code at all, but I see the utility to allowing dynamic updates. I researched Stencil and I see how this is done so I'll work on an update.

**Comment by jf990** [comment]
Reactive attributes added in version 0.8.1

**Comment by gavinr** [comment]
Great, thanks! Here's an updated example using v0.8.1:
https://codepen.io/gavinr/pen/GRaMpMX?editors=1000
